"""initial schema

Revision ID: 115ed2b5049d
Revises: 
Create Date: 2026-06-12 17:23:32.790189
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '115ed2b5049d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_position'), 'lesson', ['position'], unique=False)
    op.create_index(op.f('ix_lesson_slug'), 'lesson', ['slug'], unique=True)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statement_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starter_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solution_module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_lesson_id'), 'exercise', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_exercise_position'), 'exercise', ['position'], unique=False)
    op.create_index(op.f('ix_exercise_slug'), 'exercise', ['slug'], unique=False)
    op.create_table('exercise_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_test_exercise_id'), 'exercise_test', ['exercise_id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PASSED', 'FAILED', 'ERROR', 'TIMEOUT', name='submissionstatus'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_created_at'), 'submission', ['created_at'], unique=False)
    op.create_index(op.f('ix_submission_exercise_id'), 'submission', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_submission_status'), 'submission', ['status'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_submission_id', sa.Integer(), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_submission_id'], ['submission.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_exercise_id'), 'progress', ['exercise_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_exercise_id'), table_name='progress')
    op.drop_table('progress')
    op.drop_index(op.f('ix_submission_status'), table_name='submission')
    op.drop_index(op.f('ix_submission_exercise_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_created_at'), table_name='submission')
    op.drop_table('submission')
    op.drop_index(op.f('ix_exercise_test_exercise_id'), table_name='exercise_test')
    op.drop_table('exercise_test')
    op.drop_index(op.f('ix_exercise_slug'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_position'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_lesson_id'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_lesson_slug'), table_name='lesson')
    op.drop_index(op.f('ix_lesson_position'), table_name='lesson')
    op.drop_table('lesson')
    # ### end Alembic commands ###
